/* ===== Phiên âm tiếng Anh =====
   Phiên âm giọng Anh - Anh, viết theo lối sách giáo khoa ở Việt Nam.
   Nguồn: bộ dữ liệu mở open-dict-data/ipa-dict (en_UK, giấy phép MIT), nắn
   lại cho đúng lối viết quen thuộc — đổi ɹ thành r, ɛ thành e, và lùi dấu
   trọng âm về đầu âm tiết thay vì đặt ngay trước nguyên âm. Bảy mươi từ bộ
   đó không có (tên tháng, thứ trong tuần, mấy câu chào hỏi) thì viết tay.

   Câu dài như "nice to meet you" cố ý để trống: ghi phiên âm cả câu thì dài
   dòng mà bé cũng không đọc theo được.
*/
(function (global) {
  'use strict';

  var KHO = {
    'April': '/ˈeɪprəl/',
    'August': '/ˈɔːɡəst/',
    'Be careful': '/ˈbiː ˈkeəfəl/',
    'Christmas tree': '/ˈkrɪsməs triː/',
    'December': '/dɪˈsembə/',
    'Don\'t worry': '/dəʊnt ˈwʌri/',
    'English': '/ˈɪŋɡlɪʃ/',
    'Excuse me': '/ɪkˈskjuːz miː/',
    'February': '/ˈfebruəri/',
    'Friday': '/ˈfraɪdeɪ/',
    'Hurry up': '/ˈhʌri ˈʌp/',
    'I': '/aɪ/',
    'I agree': '/aɪ əˈɡriː/',
    'I forgot': '/aɪ fəˈɡɒt/',
    'I understand': '/aɪ ˌʌndəˈstænd/',
    'I\'m fine': '/aɪm faɪn/',
    'I\'m full': '/aɪm fʊl/',
    'I\'m tired': '/aɪm ˈtaɪəd/',
    'It\'s okay': '/ɪts əʊˈkeɪ/',
    'It\'s time': '/ɪts taɪm/',
    'January': '/ˈdʒænjuəri/',
    'July': '/dʒuˈlaɪ/',
    'June': '/dʒuːn/',
    'Let\'s go': '/lets ɡəʊ/',
    'Let\'s play': '/lets pleɪ/',
    'March': '/mɑːtʃ/',
    'May': '/meɪ/',
    'Maybe': '/ˈmeɪbiː/',
    'Monday': '/ˈmʌndeɪ/',
    'My favourite is…': '/ˈmaɪ ˈfeɪvrɪt ˈɪz/',
    'November': '/nəʊˈvembə/',
    'October': '/ɒkˈtəʊbə/',
    'Of course': '/ˈɒv ˈkɔːs/',
    'PE': '/ˌpiː ˈiː/',
    'Santa': '/ˈsæntə/',
    'Saturday': '/ˈsætədeɪ/',
    'September': '/sepˈtembə/',
    'Sunday': '/ˈsʌndeɪ/',
    'Thursday': '/ˈθɜːzdeɪ/',
    'Tuesday': '/ˈtjuːzdeɪ/',
    'UFO': '/ˌjuː ef ˈəʊ/',
    'Wednesday': '/ˈwenzdeɪ/',
    'a bit': '/ə bɪt/',
    'across': '/əˈkrɒs/',
    'air': '/ˈeə/',
    'alarm clock': '/əˈlɑːm ˈklɒk/',
    'all': '/ˈɔːl/',
    'also': '/ˈɒlsəʊ/',
    'always': '/ˈɔːlweɪz/',
    'amazed': '/əˈmeɪzd/',
    'ambulance': '/ˈæmbjʊləns/',
    'and': '/ˈænd/',
    'angry': '/ˈæŋɡri/',
    'answer': '/ˈɑːnsə/',
    'ant': '/ˈænt/',
    'apple': '/ˈæpəl/',
    'arm': '/ˈɑːm/',
    'around': '/əˈraʊnd/',
    'art': '/ˈɑːt/',
    'artist': '/ˈɑːtɪst/',
    'ask': '/ˈɑːsk/',
    'astronaut': '/ˈæstrəˌnɔːt/',
    'autumn': '/ˈɔːtʌm/',
    'avocado': '/ˌævəˈkɑːdəʊ/',
    'baby': '/ˈbeɪbi/',
    'bad': '/ˈbæd/',
    'badminton': '/ˈbædmɪntən/',
    'ball': '/ˈbɔːl/',
    'balloon': '/bəˈluːn/',
    'banana': '/bəˈnɑːnə/',
    'bank': '/ˈbæŋk/',
    'bank card': '/ˈbæŋk ˈkɑːd/',
    'banknote': '/ˈbænknəʊt/',
    'basket': '/ˈbɑːskɪt/',
    'basketball': '/ˈbɑːskɪtˌbɔːl/',
    'bat': '/ˈbæt/',
    'bathtub': '/ˈbɑːθtʌb/',
    'battery': '/ˈbætəri/',
    'be off sick': '/ˈbiː ˈɒf ˈsɪk/',
    'be quiet': '/ˈbiː ˈkwaɪət/',
    'beach': '/ˈbiːtʃ/',
    'beautiful': '/ˈbjuːtɪfəl/',
    'because': '/bɪˈkʌz/',
    'bed': '/ˈbed/',
    'bee': '/ˈbiː/',
    'behind': '/bɪˈhaɪnd/',
    'bell': '/ˈbel/',
    'between': '/bɪˈtwiːn/',
    'bicycle': '/ˈbaɪsɪkəl/',
    'big': '/ˈbɪɡ/',
    'big brother': '/ˈbɪɡ ˈbrʌðə/',
    'big sister': '/ˈbɪɡ ˈsɪstə/',
    'bin': '/ˈbɪn/',
    'bird': '/ˈbɜːd/',
    'birthday cake': '/ˈbɜːθdeɪ ˈkeɪk/',
    'biscuit': '/ˈbɪskɪt/',
    'bitter': '/ˈbɪtə/',
    'black': '/ˈblæk/',
    'blackboard': '/ˈblækbɔːd/',
    'blue': '/ˈbluː/',
    'blueberry': '/ˈbluːberi/',
    'boat': '/ˈbəʊt/',
    'bone': '/ˈbəʊn/',
    'book': '/ˈbʊk/',
    'boots': '/ˈbuːts/',
    'boring': '/ˈbɔːrɪŋ/',
    'bottle': '/ˈbɒtəl/',
    'bowl': '/ˈbəʊl/',
    'brain': '/ˈbreɪn/',
    'brave': '/ˈbreɪv/',
    'bread': '/ˈbred/',
    'break time': '/ˈbreɪk ˈtaɪm/',
    'bride': '/ˈbraɪd/',
    'bridge': '/ˈbrɪdʒ/',
    'bright': '/ˈbraɪt/',
    'bring': '/ˈbrɪŋ/',
    'broccoli': '/ˈbrɒkəˌli/',
    'broom': '/ˈbruːm/',
    'brothers': '/ˈbrʌðəz/',
    'brown': '/ˈbraʊn/',
    'brush your teeth': '/ˈbrʌʃ ˈjɔː ˈtiːθ/',
    'bubble tea': '/ˈbʌbəl ˈtiː/',
    'bucket': '/ˈbʌkɪt/',
    'bun': '/ˈbʌn/',
    'burger': '/ˈbɜːɡə/',
    'bus': '/ˈbʌs/',
    'bus stop': '/ˈbʌs ˈstɒp/',
    'busy': '/ˈbɪzi/',
    'but': '/ˈbʌt/',
    'butterfly': '/ˈbʌtəˌflaɪ/',
    'buy': '/ˈbaɪ/',
    'cactus': '/ˈkæktəs/',
    'cage': '/ˈkeɪdʒ/',
    'cake': '/ˈkeɪk/',
    'calculator': '/ˈkælkjʊˌleɪtə/',
    'calendar': '/ˈkæləndə/',
    'calm': '/ˈkɑːm/',
    'camel': '/ˈkæməl/',
    'camera': '/ˈkæmrə/',
    'candle': '/ˈkændəl/',
    'candy': '/ˈkændi/',
    'car': '/ˈkɑː/',
    'carefully': '/ˈkeəfəli/',
    'carrot': '/ˈkærət/',
    'castle': '/ˈkɑːsəl/',
    'cat': '/ˈkæt/',
    'catch': '/ˈkætʃ/',
    'cave': '/keɪv/',
    'certificate': '/səˈtɪfɪkət/',
    'chair': '/tˈʃeə/',
    'change': '/tˈʃeɪndʒ/',
    'cheap': '/tˈʃiːp/',
    'cheese': '/tˈʃiːz/',
    'chef': '/ˈʃef/',
    'cherry': '/tˈʃeri/',
    'chess': '/tˈʃes/',
    'chick': '/tˈʃɪk/',
    'chicken': '/tˈʃɪkɪn/',
    'chilli': '/tˈʃɪli/',
    'chips': '/tˈʃɪps/',
    'chocolate': '/tˈʃɒklət/',
    'church': '/tˈʃɜːtʃ/',
    'circle': '/ˈsɜːkəl/',
    'clean': '/ˈkliːn/',
    'clever': '/ˈklevə/',
    'climb': '/ˈklaɪm/',
    'clock': '/ˈklɒk/',
    'close': '/kləʊz/',
    'cloud': '/ˈklaʊd/',
    'coat': '/ˈkəʊt/',
    'coconut': '/ˈkəʊkəˌnʌt/',
    'coffee': '/ˈkɒfi/',
    'coin': '/ˈkɔɪn/',
    'cold': '/ˈkəʊld/',
    'cold (illness)': '/ˈkəʊld ˈɪlnəs/',
    'come': '/ˈkʌm/',
    'comet': '/ˈkɒmɪt/',
    'computer': '/kəmˈpjuːtə/',
    'confused': '/kənˈfjuːzd/',
    'cook': '/ˈkʊk/',
    'cool': '/ˈkuːl/',
    'coral': '/ˈkɒrəl/',
    'corn': '/ˈkɔːn/',
    'cough': '/ˈkɒf/',
    'count': '/ˈkaʊnt/',
    'cow': '/ˈkaʊ/',
    'crab': '/ˈkræb/',
    'cradle': '/ˈkreɪdəl/',
    'crayons': '/ˈkreɪɒnz/',
    'cricket': '/ˈkrɪkɪt/',
    'crocodile': '/ˈkrɒkəˌdaɪl/',
    'cross the road': '/ˈkrɒs ðə ˈrəʊd/',
    'cry': '/ˈkraɪ/',
    'cucumber': '/ˈkjuːkʌmbə/',
    'cup': '/ˈkʌp/',
    'cut': '/ˈkʌt/',
    'cycling': '/ˈsaɪklɪŋ/',
    'dad': '/ˈdæd/',
    'dance': '/ˈdɑːns/',
    'dark': '/ˈdɑːk/',
    'deep': '/ˈdiːp/',
    'deer': '/ˈdiə/',
    'delicious': '/dɪˈlɪʃəs/',
    'desert': '/ˈdezət/',
    'diamond': '/ˈdaɪəmənd/',
    'difficult': '/ˈdɪfɪkəlt/',
    'directions': '/daɪˈrekʃənz/',
    'dirty': '/ˈdɜːti/',
    'disappointed': '/ˌdɪsəˈpɔɪntɪd/',
    'do homework': '/duː ˈhəʊmwɜːk/',
    'doctor': '/ˈdɒktə/',
    'dog': '/ˈdɒɡ/',
    'doll': '/ˈdɒl/',
    'dolphin': '/ˈdɒlfɪn/',
    'donkey': '/ˈdɒŋki/',
    'door': '/ˈdɔː/',
    'down': '/ˈdaʊn/',
    'draw': '/ˈdrɔː/',
    'dress': '/ˈdres/',
    'drink': '/ˈdrɪŋk/',
    'drum': '/ˈdrʌm/',
    'dry': '/ˈdraɪ/',
    'duck': '/ˈdʌk/',
    'eagle': '/ˈiːɡəl/',
    'ear': '/ˈiə/',
    'easy': '/ˈiːzi/',
    'eat': '/ˈiːt/',
    'egg': '/ˈeɡ/',
    'eighteen': '/eɪˈtiːn/',
    'elephant': '/ˈelɪfənt/',
    'eleven': '/ɪˈlevən/',
    'empty': '/ˈempti/',
    'evening': '/ˈiːvnɪŋ/',
    'everyone': '/ˈevrɪˌwɒn/',
    'excited': '/ekˈsaɪtɪd/',
    'eye': '/ˈaɪ/',
    'factory': '/ˈfæktəˌri/',
    'family': '/ˈfæmɪli/',
    'fan': '/ˈfæn/',
    'far': '/ˈfɑː/',
    'farm': '/ˈfɑːm/',
    'farmer': '/ˈfɑːmə/',
    'fast': '/ˈfɑːst/',
    'feather': '/ˈfeðə/',
    'fever': '/ˈfiːvə/',
    'field': '/ˈfiːld/',
    'fifteen': '/fɪfˈtiːn/',
    'fifty': '/ˈfɪfti/',
    'finally': '/ˈfaɪnəli/',
    'find': '/ˈfaɪnd/',
    'finger': '/ˈfɪŋɡə/',
    'finish': '/ˈfɪnɪʃ/',
    'fire truck': '/ˈfaɪə ˈtrʌk/',
    'firefighter': '/ˈfaɪəfaɪtə/',
    'fireworks': '/ˈfaɪəwɜːks/',
    'first': '/ˈfɜːst/',
    'fish': '/ˈfɪʃ/',
    'flamingo': '/fleˈmɪŋɡəʊ/',
    'flute': '/ˈfluːt/',
    'fly': '/ˈflaɪ/',
    'fog': '/ˈfɒɡ/',
    'folder': '/ˈfəʊldə/',
    'foot': '/ˈfʊt/',
    'forest': '/ˈfɒrɪst/',
    'forget': '/fəˈɡet/',
    'fork': '/ˈfɔːk/',
    'forty': '/ˈfɔːti/',
    'fountain pen': '/ˈfaʊntɪn ˈpen/',
    'fourteen': '/fɔːˈtiːn/',
    'fox': '/ˈfɒks/',
    'free': '/ˈfriː/',
    'fried chicken': '/ˈfraɪd tˈʃɪkɪn/',
    'friend': '/ˈfrend/',
    'friendly': '/ˈfrendli/',
    'full': '/ˈfʊl/',
    'funny': '/ˈfʌni/',
    'fur': '/ˈfɜː/',
    'galaxy': '/ˈɡæləkˌsi/',
    'garlic': '/ˈɡɑːlɪk/',
    'generous': '/dˈʒenərəs/',
    'geography': '/dʒɪˈɒɡrəfi/',
    'get dressed': '/ˈɡet ˈdrest/',
    'get lost': '/ˈɡet ˈlɒst/',
    'ginger': '/dˈʒɪndʒə/',
    'give': '/ˈɡɪv/',
    'glad': '/ˈɡlæd/',
    'glasses': '/ˈɡlɑːsɪz/',
    'globe': '/ˈɡləʊb/',
    'gloves': '/ˈɡlʌvz/',
    'go': '/ˈɡəʊ/',
    'go home': '/ˈɡəʊ ˈhəʊm/',
    'go shopping': '/ˈɡəʊ ˈʃɒpɪŋ/',
    'go straight': '/ˈɡəʊ ˈstreɪt/',
    'go to bed': '/ˈɡəʊ ˈtuː ˈbed/',
    'go to school': '/ˈɡəʊ ˈtuː ˈskuːl/',
    'goat': '/ˈɡəʊt/',
    'good': '/ˈɡʊd/',
    'good luck': '/ˈɡʊd ˈlʌk/',
    'good morning': '/ˈɡʊd ˈmɔːnɪŋ/',
    'good night': '/ˈɡʊd ˈnaɪt/',
    'goodbye': '/ɡʊdˈbaɪ/',
    'goose': '/ˈɡuːs/',
    'gorilla': '/ɡəˈrɪlə/',
    'grandma': '/ˈɡrændmɑː/',
    'grandpa': '/ˈɡrændpɑː/',
    'grapes': '/ˈɡreɪps/',
    'grass': '/ˈɡrɑːs/',
    'green': '/ˈɡriːn/',
    'grey': '/ˈɡreɪ/',
    'ground': '/ˈɡraʊnd/',
    'guitar': '/ɡɪˈtɑː/',
    'hair': '/ˈheə/',
    'half': '/ˈhɑːf/',
    'hammer': '/ˈhæmə/',
    'hamster': '/ˈhæmstə/',
    'hand': '/ˈhænd/',
    'handbag': '/ˈhændbæɡ/',
    'happy': '/ˈhæpi/',
    'happy birthday': '/ˈhæpi ˈbɜːθdeɪ/',
    'hard': '/ˈhɑːd/',
    'hard-working': '/ˌhɑːd ˈwɜːkɪŋ/',
    'hat': '/ˈhæt/',
    'hate': '/ˈheɪt/',
    'have breakfast': '/hæv ˈbrekfəst/',
    'have dinner': '/hæv ˈdɪnə/',
    'have lunch': '/hæv lʌntʃ/',
    'he': '/hiː/',
    'headache': '/ˈhedeɪk/',
    'headphones': '/ˈhedfəʊnz/',
    'healthy': '/ˈhelθi/',
    'heart': '/ˈhɑːt/',
    'heart (organ)': '/ˈhɑːt ˈɔːɡən/',
    'heavy': '/ˈhevi/',
    'hedgehog': '/ˈhedʒhɒɡ/',
    'helicopter': '/ˈhelɪˌkɒptə/',
    'hello': '/həˈləʊ/',
    'help': '/ˈhelp/',
    'here': '/ˈhiə/',
    'hill': '/ˈhɪl/',
    'hippo': '/ˈhɪpəʊ/',
    'history': '/ˈhɪstəˌri/',
    'home time': '/ˈhəʊm ˈtaɪm/',
    'homework': '/ˈhəʊmwɜːk/',
    'honest': '/ˈɒnɪst/',
    'honey': '/ˈhʌni/',
    'horn': '/ˈhɔːn/',
    'hospital': '/ˈhɒspɪtəl/',
    'hot': '/ˈhɒt/',
    'hour': '/ˈaʊə/',
    'hourglass': '/ˈaʊəɡlɑːs/',
    'house': '/haʊs/',
    'housefly': '/ˈhaʊsflaɪ/',
    'how': '/ˈhaʊ/',
    'how many': '/ˈhaʊ ˈmeni/',
    'how much is it?': '/ˈhaʊ ˈmʌtʃ ˈɪz ˈɪt/',
    'hungry': '/ˈhʌŋɡri/',
    'ice': '/ˈaɪs/',
    'ice cream': '/ˈaɪs ˈkriːm/',
    'if': '/ˈɪf/',
    'in': '/ˈɪn/',
    'in front of': '/ˈɪn ˈfrʌnt ˈɒv/',
    'into': '/ˈɪntʊ/',
    'island': '/ˈaɪlənd/',
    'it': '/ˈɪt/',
    'it\'s delicious': '/ɪts dɪˈlɪʃəs/',
    'jellyfish': '/dˈʒelɪfɪʃ/',
    'juice': '/dˈʒuːs/',
    'jump': '/dˈʒʌmp/',
    'kangaroo': '/ˈkæŋɡəˌruː/',
    'key': '/ˈkiː/',
    'kind': '/ˈkaɪnd/',
    'kite': '/ˈkaɪt/',
    'kitten': '/ˈkɪtən/',
    'kiwi': '/ˈkiːwiː/',
    'knife': '/ˈnaɪf/',
    'know': '/ˈnəʊ/',
    'ladybug': '/ˈleɪdɪˌbʌɡ/',
    'lake': '/ˈleɪk/',
    'lamp': '/ˈlæmp/',
    'last': '/ˈlɑːst/',
    'laughing': '/ˈlɑːfɪŋ/',
    'lazy': '/ˈleɪzi/',
    'left': '/ˈleft/',
    'leg': '/ˈleɡ/',
    'lemon': '/ˈlemən/',
    'lettuce': '/ˈletɪs/',
    'lie down': '/ˈlaɪ ˈdaʊn/',
    'light': '/ˈlaɪt/',
    'light blue': '/ˈlaɪt ˈbluː/',
    'lightning': '/ˈlaɪtnɪŋ/',
    'like': '/ˈlaɪk/',
    'line up': '/ˈlaɪn ˈʌp/',
    'listen': '/ˈlɪsən/',
    'listen to me': '/ˈlɪsən ˈtuː ˈmiː/',
    'lizard': '/ˈlɪzəd/',
    'lobster': '/ˈlɒbstə/',
    'lock': '/ˈlɒk/',
    'long': '/ˈlɒŋ/',
    'look': '/ˈlʊk/',
    'look at the board': '/ˈlʊk ˈæt ðə ˈbɔːd/',
    'love': '/ˈlʌv/',
    'low': '/ˈləʊ/',
    'lungs': '/ˈlʌŋz/',
    'magnet': '/ˈmæɡnɪt/',
    'make': '/ˈmeɪk/',
    'mango': '/ˈmæŋɡəʊ/',
    'many': '/ˈmeni/',
    'map': '/ˈmæp/',
    'mark': '/ˈmɑːk/',
    'maths': '/mæθs/',
    'meat': '/ˈmiːt/',
    'mechanic': '/mɪˈkænɪk/',
    'medal': '/ˈmedəl/',
    'medicine': '/ˈmedsən/',
    'melon': '/ˈmelən/',
    'menu': '/ˈmenjuː/',
    'microphone': '/ˈmaɪkrəˌfəʊn/',
    'microscope': '/ˈmaɪkrəˌskəʊp/',
    'milk': '/ˈmɪlk/',
    'minute': '/ˈmɪnɪt/',
    'mirror': '/ˈmɪrə/',
    'month': '/ˈmʌnθ/',
    'morning': '/ˈmɔːnɪŋ/',
    'mosquito': '/məˈskiːtəʊ/',
    'motorbike': '/ˈməʊtəˌbaɪk/',
    'mouse': '/maʊs/',
    'mouth': '/maʊθ/',
    'mum': '/ˈmʌm/',
    'mushroom': '/ˈmʌʃruːm/',
    'music': '/ˈmjuːzɪk/',
    'music note': '/ˈmjuːzɪk ˈnəʊt/',
    'my': '/ˈmaɪ/',
    'my name is…': '/ˈmaɪ ˈneɪm ˈɪz/',
    'narrow': '/ˈnærəʊ/',
    'near': '/ˈniə/',
    'need': '/ˈniːd/',
    'nest': '/ˈnest/',
    'never': '/ˈnevə/',
    'new': '/ˈnjuː/',
    'next to': '/ˈnekst ˈtuː/',
    'night': '/ˈnaɪt/',
    'nineteen': '/naɪnˈtiːn/',
    'no': '/nəʊ/',
    'noisy': '/ˈnɔɪzi/',
    'noodles': '/ˈnuːdəlz/',
    'nose': '/ˈnəʊz/',
    'notebook': '/ˈnəʊtbʊk/',
    'nothing': '/ˈnʌθɪŋ/',
    'now': '/ˈnaʊ/',
    'octopus': '/ˈɒktəpəs/',
    'old': '/ˈəʊld/',
    'olive': '/ˈɒlɪv/',
    'on': '/ˈɒn/',
    'one hundred': '/ˈwɒn ˈhʌndrəd/',
    'one thousand': '/ˈwɒn ˈθaʊzənd/',
    'onion': '/ˈʌniən/',
    'open': '/ˈəʊpən/',
    'open your book': '/ˈəʊpən ˈjɔː ˈbʊk/',
    'or': '/ˈɔː/',
    'orange': '/ˈɒrɪndʒ/',
    'order': '/ˈɔːdə/',
    'out': '/ˈaʊt/',
    'outside': '/ˌaʊtˈsaɪd/',
    'owl': '/ˈaʊl/',
    'pack': '/ˈpæk/',
    'palm tree': '/ˈpɑːm ˈtriː/',
    'pan': '/pæn/',
    'pancake': '/ˈpænkeɪk/',
    'panda': '/ˈpændə/',
    'paper': '/ˈpeɪpə/',
    'paper clip': '/ˈpeɪpə ˈklɪp/',
    'parasol': '/ˈpærəˌsɒl/',
    'park': '/ˈpɑːk/',
    'parrot': '/ˈpærət/',
    'patient': '/ˈpeɪʃənt/',
    'pavement': '/ˈpeɪvmənt/',
    'pay': '/ˈpeɪ/',
    'peach': '/ˈpiːtʃ/',
    'peacock': '/ˈpiːkɒk/',
    'peanut': '/ˈpiːnʌt/',
    'pear': '/ˈpeə/',
    'pen': '/ˈpen/',
    'penguin': '/ˈpeŋɡwɪn/',
    'pet food': '/ˈpet ˈfuːd/',
    'pho noodles': '/fə ˈnuːdlz/',
    'phone': '/ˈfəʊn/',
    'piano': '/pɪˈænəʊ/',
    'pig': '/ˈpɪɡ/',
    'pilot': '/ˈpaɪlət/',
    'pineapple': '/ˈpaɪnæpəl/',
    'pink': '/ˈpɪŋk/',
    'pizza': '/ˈpiːtsə/',
    'plane': '/ˈpleɪn/',
    'planet': '/ˈplænɪt/',
    'plant pot': '/ˈplænt ˈpɒt/',
    'plate': '/ˈpleɪt/',
    'play': '/ˈpleɪ/',
    'please': '/ˈpliːz/',
    'pleased': '/ˈpliːzd/',
    'police car': '/pəˈliːs ˈkɑː/',
    'police officer': '/pəˈliːs ˈɒfɪsə/',
    'polite': '/pəˈlaɪt/',
    'poor': '/ˈpɔː/',
    'pot': '/ˈpɒt/',
    'potato': '/pəˈteɪtəʊ/',
    'present': '/ˈpreznt/',
    'price tag': '/ˈpraɪs ˈtæɡ/',
    'proud': '/ˈpraʊd/',
    'pull': '/ˈpʊl/',
    'pumpkin': '/ˈpʌmpkɪn/',
    'puppy': '/ˈpʌpi/',
    'purple': '/ˈpɜːpəl/',
    'push': '/ˈpʊʃ/',
    'puzzle': '/ˈpʌzəl/',
    'quickly': '/ˈkwɪkli/',
    'quiet': '/ˈkwaɪət/',
    'rabbit': '/ˈræbɪt/',
    'radio': '/ˈreɪdɪˌəʊ/',
    'rainbow': '/ˈreɪnbəʊ/',
    'rainy': '/ˈreɪni/',
    'rarely': '/ˈreəli/',
    'read': '/riːd/',
    'receipt': '/rɪˈsiːt/',
    'red': '/ˈred/',
    'remember': '/rɪˈmembə/',
    'repeat after me': '/rɪˈpiːt ˈɑːftə ˈmiː/',
    'rest': '/ˈrest/',
    'rhino': '/ˈraɪnəʊ/',
    'rice': '/ˈraɪs/',
    'rich': '/ˈrɪtʃ/',
    'right': '/ˈraɪt/',
    'right (side)': '/ˈraɪt ˈsaɪd/',
    'ring': '/ˈrɪŋ/',
    'river': '/ˈrɪvə/',
    'rocket': '/ˈrɒkɪt/',
    'rooster': '/ˈruːstə/',
    'rose': '/rəʊz/',
    'rugby ball': '/ˈrʌɡbi ˈbɔːl/',
    'ruler': '/ˈruːlə/',
    'run': '/ˈrʌn/',
    'running': '/ˈrʌnɪŋ/',
    'sad': '/ˈsæd/',
    'salad': '/ˈsæləd/',
    'salt': '/ˈsɒlt/',
    'salty': '/ˈsɒlti/',
    'sand': '/ˈsænd/',
    'sandals': '/ˈsændəlz/',
    'sandwich': '/ˈsændwɪtʃ/',
    'satellite': '/ˈsætəˌlaɪt/',
    'sausage': '/ˈsɒsɪdʒ/',
    'saw': '/ˈsɔː/',
    'say it again, please': '/ˈseɪ ˈɪt əˈɡen ˈpliːz/',
    'scale': '/ˈskeɪl/',
    'scared': '/ˈskeəd/',
    'scarf': '/ˈskɑːf/',
    'school': '/ˈskuːl/',
    'school bag': '/ˈskuːl ˈbæɡ/',
    'science': '/ˈsaɪəns/',
    'scientist': '/ˈsaɪəntɪst/',
    'scissors': '/ˈsɪsəz/',
    'scooter': '/ˈskuːtə/',
    'screw': '/ˈskruː/',
    'screwdriver': '/ˈskruːdraɪvə/',
    'seal': '/ˈsiːl/',
    'second': '/ˈsekənd/',
    'second (order)': '/ˈsekənd/',
    'see you': '/ˈsiː ˈjuː/',
    'seed': '/ˈsiːd/',
    'selfish': '/ˈselfɪʃ/',
    'sell': '/ˈsel/',
    'serious': '/ˈsiərɪəs/',
    'set square': '/ˈset ˈskweə/',
    'seventeen': '/ˌsevənˈtiːn/',
    'shallow': '/ˈʃæləʊ/',
    'share': '/ˈʃeə/',
    'shark': '/ˈʃɑːk/',
    'she': '/ˈʃiː/',
    'sheep': '/ˈʃiːp/',
    'shell': '/ˈʃel/',
    'ship': '/ˈʃɪp/',
    'shirt': '/ˈʃɜːt/',
    'shoes': '/ˈʃuːz/',
    'shop': '/ˈʃɒp/',
    'short': '/ˈʃɔːt/',
    'shorts': '/ˈʃɔːts/',
    'shower': '/ˈʃaʊə/',
    'shrimp': '/ˈʃrɪmp/',
    'shy': '/ˈʃaɪ/',
    'sick': '/ˈsɪk/',
    'sing': '/ˈsɪŋ/',
    'sisters': '/ˈsɪstəz/',
    'sit': '/ˈsɪt/',
    'sit down': '/ˈsɪt ˈdaʊn/',
    'sixteen': '/sɪkˈstiːn/',
    'skateboard': '/ˈskeɪtbɔːd/',
    'sky': '/ˈskaɪ/',
    'sleep': '/ˈsliːp/',
    'sleepy': '/ˈsliːpi/',
    'sloth': '/ˈslɒθ/',
    'slow': '/ˈsləʊ/',
    'small': '/ˈsmɔːl/',
    'smile': '/ˈsmaɪl/',
    'snail': '/ˈsneɪl/',
    'snake': '/ˈsneɪk/',
    'snow': '/ˈsnəʊ/',
    'snowman': '/ˈsnəʊmən/',
    'soap': '/ˈsəʊp/',
    'socks': '/ˈsɒks/',
    'sofa': '/ˈsəʊfə/',
    'soft': '/ˈsɒft/',
    'some': '/ˈsʌm/',
    'sometimes': '/ˈsʌmtaɪmz/',
    'sorry': '/ˈsɒri/',
    'sour': '/ˈsaʊə/',
    'spade': '/ˈspeɪd/',
    'spanner': '/ˈspænə/',
    'speak': '/ˈspiːk/',
    'spicy': '/ˈspaɪsi/',
    'spider': '/ˈspaɪdə/',
    'spoon': '/ˈspuːn/',
    'spring': '/ˈsprɪŋ/',
    'squid': '/skwɪd/',
    'stadium': '/ˈsteɪdiəm/',
    'stairs': '/ˈsteəz/',
    'stand': '/ˈstænd/',
    'stand up': '/ˈstænd ˈʌp/',
    'star shape': '/ˈstɑː ˈʃeɪp/',
    'start': '/ˈstɑːt/',
    'stomach ache': '/ˈstʌmək eɪk/',
    'stop': '/ˈstɒp/',
    'storm': '/ˈstɔːm/',
    'strawberry': '/ˈstrɔːbəri/',
    'strong': '/ˈstrɒŋ/',
    'summer': '/ˈsʌmə/',
    'sun hat': '/ˈsʌn ˈhæt/',
    'sunny': '/ˈsʌni/',
    'surprised': '/səˈpraɪzd/',
    'swan': '/ˈswɒn/',
    'sweater': '/ˈswetə/',
    'sweep the floor': '/ˈswiːp ðə ˈflɔː/',
    'sweet': '/ˈswiːt/',
    'swim': '/ˈswɪm/',
    'swimming': '/ˈswɪmɪŋ/',
    'swimsuit': '/ˈswɪmsuːt/',
    'tail': '/ˈteɪl/',
    'take': '/ˈteɪk/',
    'tall': '/ˈtɔːl/',
    'taxi': '/ˈtæksi/',
    'tea': '/ˈtiː/',
    'teacher': '/ˈtiːtʃə/',
    'teapot': '/ˈtiːpɒt/',
    'teddy bear': '/ˈtedi ˈbeə/',
    'telescope': '/ˈtelɪˌskəʊp/',
    'television': '/ˈtelɪˌvɪʒən/',
    'tennis': '/ˈtenɪs/',
    'test': '/ˈtest/',
    'test tube': '/ˈtest ˈtjuːb/',
    'thank you': '/ˈθæŋk ˈjuː/',
    'that': '/ˈðæt/',
    'the Earth': '/ðə ˈɜːθ/',
    'then': '/ˈðen/',
    'there': '/ˈðeə/',
    'thermometer': '/θɜːˈmɒmɪtə/',
    'they': '/ˈðeɪ/',
    'think': '/ˈθɪŋk/',
    'third': '/ˈθɜːd/',
    'thirsty': '/ˈθɜːsti/',
    'thirteen': '/θɜːˈtiːn/',
    'thirty': '/ˈθɜːti/',
    'this': '/ˈðɪs/',
    'throw': '/ˈθrəʊ/',
    'ticket': '/ˈtɪkɪt/',
    'tidy up': '/ˈtaɪdi ˈʌp/',
    'tie': '/ˈtaɪ/',
    'timetable': '/ˈtaɪmteɪbəl/',
    'tired': '/ˈtaɪəd/',
    'today': '/təˈdeɪ/',
    'toilet paper': '/ˈtɔɪlət ˈpeɪpə/',
    'tomato': '/təˈmɑːtəʊ/',
    'tomorrow': '/təˈmɒrəʊ/',
    'tongue': '/ˈtʌŋ/',
    'too': '/ˈtuː/',
    'tooth': '/ˈtuːθ/',
    'toothache': '/ˈtuːθeɪk/',
    'toothbrush': '/ˈtuːθbrʌʃ/',
    'torch': '/ˈtɔːtʃ/',
    'tractor': '/ˈtræktə/',
    'traffic light': '/ˈtræfɪk ˈlaɪt/',
    'train': '/ˈtreɪn/',
    'tram': '/ˈtræm/',
    'triangle': '/ˈtraɪæŋɡəl/',
    'trip': '/ˈtrɪp/',
    'trophy': '/ˈtrəʊfi/',
    'tropical fish': '/ˈtrɒpɪkəl ˈfɪʃ/',
    'trousers': '/ˈtraʊsəz/',
    'truck': '/ˈtrʌk/',
    'trumpet': '/ˈtrʌmpɪt/',
    'try': '/ˈtraɪ/',
    'try again': '/ˈtraɪ əˈɡen/',
    'tulip': '/ˈtjuːlɪp/',
    'turn left': '/ˈtɜːn ˈleft/',
    'turn right': '/ˈtɜːn ˈraɪt/',
    'turtle': '/ˈtɜːtəl/',
    'twelve': '/ˈtwelv/',
    'twenty': '/ˈtwenti/',
    'ugly': '/ˈʌɡli/',
    'umbrella': '/ʌmˈbrelə/',
    'under': '/ˈʌndə/',
    'up': '/ˈʌp/',
    'usually': '/ˈjuːʒuːəli/',
    'very': '/ˈveri/',
    'violin': '/vaɪəˈlɪn/',
    'volcano': '/vɒlˈkeɪnəʊ/',
    'volleyball': '/ˈvɒlɪˌbɔːl/',
    'wait': '/ˈweɪt/',
    'wake up': '/ˈweɪk ˈʌp/',
    'walk': '/ˈwɔːk/',
    'wallet': '/ˈwɒlɪt/',
    'want': '/ˈwɒnt/',
    'warm': '/ˈwɔːm/',
    'wash': '/ˈwɒʃ/',
    'wash the dishes': '/ˈwɒʃ ðə ˈdɪʃɪz/',
    'wash your face': '/ˈwɒʃ ˈjɔː ˈfeɪs/',
    'watch': '/ˈwɒtʃ/',
    'water': '/ˈwɔːtə/',
    'watering can': '/ˈwɔːtərɪŋ ˈkæn/',
    'watermelon': '/ˈwɔːtəˌmelən/',
    'we': '/ˈwiː/',
    'weak': '/ˈwiːk/',
    'week': '/ˈwiːk/',
    'well done': '/ˈwel ˈdʌn/',
    'wet': '/ˈwet/',
    'whale': '/ˈweɪl/',
    'what': '/ˈwɒt/',
    'when': '/ˈwen/',
    'when (linking)': '/ˈwen ˈlɪŋkɪŋ/',
    'where': '/ˈweə/',
    'which': '/ˈwɪtʃ/',
    'white': '/ˈwaɪt/',
    'who': '/ˈhuː/',
    'why': '/ˈwaɪ/',
    'wide': '/ˈwaɪd/',
    'wind': '/wɪnd/',
    'window': '/ˈwɪndəʊ/',
    'wing': '/ˈwɪŋ/',
    'winter': '/ˈwɪntə/',
    'wipe': '/ˈwaɪp/',
    'wolf': '/ˈwʊlf/',
    'work in groups': '/ˈwɜːk ˈɪn ˈɡruːps/',
    'worker': '/ˈwɜːkə/',
    'worm': '/ˈwɜːm/',
    'worried': '/ˈwʌrɪd/',
    'write': '/ˈraɪt/',
    'wrong': '/ˈrɒŋ/',
    'year': '/ˈjiə/',
    'yellow': '/ˈjeləʊ/',
    'yes': '/ˈjes/',
    'yesterday': '/ˈjestəˌdeɪ/',
    'you': '/ˈjuː/',
    'you\'re welcome': '/jɔː ˈwelkəm/',
    'your': '/ˈjɔː/',
    'zebra': '/ˈzebrə/',
    'zoo': '/ˈzuː/'
  };

  function cua(en) {
    if (!en) return null;
    return KHO[en] || KHO[String(en).toLowerCase()] || null;
  }

  global.PhienAm = { cua: cua, KHO: KHO };
})(window);
